#220 changed fontResourceId access modifier
icerockdev/moko-resources pull request #221
Opened 2021-07-19 10:33 UTC by anton6tak

Added an android-app-compose sample, it doesn't work now

2021-07-19 17:10 UTC, Alex009 requested changes

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +    kotlin(module = "android")
already enabled in `android-app-convention`

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +    }
why this here? remove it

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +    implementation(dependencyNotation = "dev.icerock.moko:resources:0.16.2")
use project accessor

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
move libs to libs.toml and use here

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +        versionName = "1.0"
already enabled by convention

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +        applicationId = "dev.arturmavl.mrfjci"
sample id as in other sample app here

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +        kotlinCompilerVersion = "1.5.10"
but we have 1.5.20 no?

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/src/main/AndroidManifest.xml
> +    package="dev.arturmavl.mrfjci.android">
sample package please

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/build.gradle.kts
> +plugins {
copyright please

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/src/main/java/dev/arturmavl/mrfjci/android/MainActivity.kt
> +package dev.arturmavl.mrfjci.android
copyright please
and sample package

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/src/main/java/dev/arturmavl/mrfjci/android/MainActivity.kt
> +            resId = MontserratRegular.fontResourceId,
`resId = MR.fonts.Montserrat.regular.fontResourceId`

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/src/main/java/dev/arturmavl/mrfjci/android/Test.kt
> +package dev.arturmavl.mrfjci.android
not needed file

2021-07-19 17:10 UTC, Alex009 commented on sample/android-app-compose/src/main/res/layout/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
not needed file at all

2021-07-21 09:56 UTC, Tetraquark requested changes

2021-07-21 09:56 UTC, Tetraquark commented on sample/android-app-compose/src/main/java/com/icerockdev/MainActivity.kt
> + */
Add empty line here after the copyright comment, please

2021-07-21 09:56 UTC, Tetraquark commented on sample/android-app-compose/build.gradle.kts
> + */
Add empty line here after the copyright comment, please

2021-07-22 03:34 UTC, Tetraquark approved these changes

2021-07-22 03:35 UTC, merged