ios color asset support for runtime dark & light color switching
icerockdev/moko-resources pull request #370
Opened 2022-07-19 16:46 UTC by jittya

To support runtime theme switch the generated color assets files need to be copied to iosApp. which can be automated by a gradle task like below and configure it as iOS  run script.

val copyColorAssetsToIOSApp = tasks.register<Copy>("copyColorAssetsToIOSApp") {
    from("$rootDir/resources/build/generated/moko/iosMain/res/Assets.xcassets")
    into("$rootDir/iosApp/iosApp/Assets.xcassets/colors")
}

Now to get the color from the iOS app assets we need to use UIColor.colorNamed(“colorName”) function. Below extension method can be used for that

fun ColorResource.getThemeColor(): UIColor {
   return UIColor.colorNamed(this.name)!!
}

2023-01-04 12:37 UTC, benMohamed commented
Can you please accept this ?

2023-03-03 05:22 UTC, Alex009 requested changes

2023-03-03 05:22 UTC, Alex009 commented on resources/src/iosMain/kotlin/dev/icerock/moko/resources/ColorResourceExt.kt
> +    return UIColor.colorNamed(this.name)!!
need to use `UIColor.colorNamed(this.name, inBundle = this.bundle)` - with it no any additional gradle tasks require

2023-03-03 05:22 UTC, Alex009 commented on resources/src/commonMain/kotlin/dev/icerock/moko/resources/ColorResource.kt
> +sealed class ColorResource(val name: String) {
name have no sense for not apple targets. we should change `ColorResource` to expect/actual. for apple target we should have `name` and `bundle` args.
for android we should use resource arg, with generation of xml colors file.
for other targets - save current way with manual selection

2023-03-03 05:22 UTC, Alex009 commented on resources-test/src/commonMain/kotlin/dev/icerock/moko/resources/test/createColorResourceMock.kt
> +fun createColorResourceMock(): ColorResource = ColorResource.Single(Color(0, 0, 0, 0), "black")
it's apple-specific details, should be removed

2023-03-03 05:22 UTC, Alex009 commented on resources-generator/src/main/kotlin/dev/icerock/gradle/generator/ColorsGenerator.kt
> +            "Single(color = Color(0x${color.singleColor}), name = \"${color.name}\")"
here we should improve logic to support apple & android native way of colors usage. i describe it in `ColorResource` file comment

2023-03-11 11:53 UTC, Alex009 commented on resources/src/iosMain/kotlin/dev/icerock/moko/resources/ColorResourceExt.kt
> +    return UIColor.colorNamed(this.name)!!
fixed in #439

2023-03-11 11:53 UTC, Alex009 commented on resources/src/commonMain/kotlin/dev/icerock/moko/resources/ColorResource.kt
> +sealed class ColorResource(val name: String) {
fixed in #439

2023-03-11 11:53 UTC, Alex009 commented on resources-test/src/commonMain/kotlin/dev/icerock/moko/resources/test/createColorResourceMock.kt
> +fun createColorResourceMock(): ColorResource = ColorResource.Single(Color(0, 0, 0, 0), "black")
fixed in #439

2023-03-11 11:53 UTC, Alex009 commented on resources-generator/src/main/kotlin/dev/icerock/gradle/generator/ColorsGenerator.kt
> +            "Single(color = Color(0x${color.singleColor}), name = \"${color.name}\")"
fixed in #439

2023-03-24 11:53 UTC, merged