Updated to add suppressed flags
icerockdev/moko-resources pull request #389
Opened 2022-10-04 13:05 UTC by kmbisset89

This is a workaround for a multiplatform bug that exists. The IDE flags cannot find the actual even though it exists.

2022-10-04 13:30 UTC, kmbisset89 commented
@Alex009 would you mind giving me a review?

2022-10-06 05:01 UTC, Alex009 requested changes

2022-10-06 10:24 UTC, kmbisset89 commented on resources-generator/gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
Will remove.

2022-10-06 10:29 UTC, kmbisset89 commented on resources-generator/src/main/kotlin/dev/icerock/gradle/generator/MRGenerator.kt
> +            }
You are correct. Your code works wonderfully, however if you have a project that does not use commonMain the expect class throws an error saying it cannot find all the actuals even though they exist. In my case I have sourceSets jvmMain, androidMain, and desktopMain where android and desktop dependOn(jvmMain). The proposed change is an optional flag to allow others to compile while multi platform still is in work. I will mark it deprecated when it is no longer needed.

2022-10-28 06:22 UTC, Alex009 commented on resources-generator/src/main/kotlin/dev/icerock/gradle/generator/MRGenerator.kt
> +            }
please create sample project where your issue can be reproduced. i think we should not use this `NO_ACTUAL_FOR_EXPECT` suppressing, we have some bug maybe

2022-10-28 06:22 UTC, Alex009 reviewed
reproducer project required

2024-04-26 04:10 UTC, closed without merging