compose-web target with asset resource and string resource
icerockdev/moko-resources pull request #430
Opened 2023-02-25 10:37 UTC by wakaztahir

adds a web target to resources-compose and adds a expect function for asset resource to get text in a multiplatform way

2023-03-03 05:14 UTC, Alex009 requested changes

2023-03-03 05:14 UTC, Alex009 commented on resources-compose/build.gradle.kts
> +        binaries.executable()
in library executable not used

2023-03-03 05:14 UTC, Alex009 commented
also CI failed

2023-03-06 17:52 UTC, wakaztahir commented
I've made changes

2023-03-10 19:53 UTC, merged