Rollback android strings generation with escapeXml
icerockdev/moko-resources pull request #692
Opened 2024-05-02 08:22 UTC by ExNDY

fix #689

2024-05-02 09:05 UTC, Alex009 commented on samples/compose-resources-gallery/shared/src/commonMain/moko-resources/base/strings.xml
> +    <string name="font_style_text">This is text <b>bold</b> <i>italic</i> &amp; <u>underline</u> &lt;b&gt;Some Text&lt;/b&gt;</string>
please add unit-tests with checks on each supported platforms

2024-05-03 04:17 UTC, Alex009 requested changes

2024-05-03 04:17 UTC, Alex009 commented on resources-generator/src/test/kotlin/dev/icerock/gradle/generator/stringsGenerator/XmlStringsToPlatformTest.kt
> +            expected = "\\&quot; \\&apos; % @ * &amp; {}",
use """ """ to remove \\

2024-05-03 05:09 UTC, ExNDY commented on resources-generator/src/test/kotlin/dev/icerock/gradle/generator/stringsGenerator/XmlStringsToPlatformTest.kt
> +            expected = "\\&quot; \\&apos; % @ * &amp; {}",
fixed

2024-05-03 05:31 UTC, Alex009 approved these changes

2024-05-03 09:18 UTC, merged