#762 added support custom build configuration for apple target
icerockdev/moko-resources pull request #765
Opened 2024-09-06 20:26 UTC by ExNDY

closed issue #762

2024-09-07 13:43 UTC, Alex009 requested changes

2024-09-07 13:43 UTC, Alex009 commented on resources-generator/src/main/kotlin/dev/icerock/gradle/generator/platform/apple/SetupAppleUtils.kt
> +        configName.matches(".*release.*".toRegex()) -> "release"
it's still not usable for all cases.
i think we should give properties to map xcode configuration to gradle configuration.
just like `xcodeConfigurationToNativeBuildType` in cocoapods kotlin plugin.

and i see that  on 155 line we already read `xcodeConfigurationToNativeBuildType` property. so if we already read it - we incorrectly use it and this should be fixed.

for cases when in xcode used custom configurations but not used cocoapods gradle plugin we still should provide mapping just like `xcodeConfigurationToNativeBuildType` to give required control for users

2024-09-10 15:30 UTC, dalewking commented
As I reported in #769 the actual problem is one of timing. You should be using xcodeConfigurationToNativeBuildType but the problem is that you are looking at it as soon as the plug in is applied so the gradle file does not even get a chance to modify xcodeConfigurationToNativeBuildType before you have already used the default values.

2024-09-22 08:35 UTC, Alex009 approved these changes

2024-09-22 12:04 UTC, merged